### ISSUE TITLE
Error Thrown on Package Load

### ISSUE THREAD

**Issue by NxtGenCowboy** [derbl4ck/jc3mp-livemap#1]
[livemap] System started
module.js:457
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\***\packages\jc3mp-livemap-master\main.js:12:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Package 'jc3mp-livemap' loaded.

**Comment by NxtGenCowboy** [comment]
It seems the map still works but does throw that error

**Comment by derbl4ck** [comment]
In this Version, you have to do 'npm install' in the directory of the package. In the next Update you don't need to do that anymore.

**Comment by NxtGenCowboy** [comment]
Thanks!  Could you add that to the install instructions for now please?   Thank you! 

I do not think it liked that.. 

 `-- UNMET PEER DEPENDENCY eslint-plugin-import@^1.7.0
+-- UNMET PEER DEPENDENCY eslint-plugin-import@^1.7.0
+-- UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^1.2.0
`-- eslint-plugin-react@5.2.2
  `-- jsx-ast-utils@1.3.5

npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-import@^1.7.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint-plugin-import@^1.7.0 but none was installed.
npm WARN jc3mp-livemap@1.0.0 No repository field.
